### ISSUE TITLE
Bug: setTexliveEndpoint

### ISSUE THREAD

**Issue by topse** [SwiftLaTeX/SwiftLaTeX#75]
Hi,
I found the following code:
```
    PdfTeXEngine.prototype.setTexliveEndpoint = function (url) {
        if (this.latexWorker !== undefined) {
            this.latexWorker.postMessage({ 'cmd': 'settexliveurl', 'url': url });
            this.latexWorker = undefined;
        }
    };
```

I dont understand, why there is "this.latexWorker = undefined". When I try to use the compileLaTeX afterwards, I get errors.

After removing that command, it works. You find that in XeTeXEngine and PdfTeXEngine at least.

A Bug?

Best Regards,
        Tobias

**Comment by elliott-wen** [comment]
Oh. That's definitely a bug.. Could you send me a pull request please?

Thanks so much.

**Comment by topse** [comment]
Done! I hope, I got all the places...

Best Regards,
         Tobias

**Comment by feberts** [comment]
The latest release (20/02/2022) still has this bug. You should probably make a new release. Also note, that in branch *gh-pages* the bug is not fixed.
